.TH "_Identify" 3 "Wed Jun 12 2013" "Version 0.1" "IRC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Identify \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_Identify\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBNICK\fP"
.br
.ti -1c
.RI "string \fBUSER\fP"
.br
.ti -1c
.RI "string \fBNickServ\fP"
.br
.ti -1c
.RI "string \fBJOIN\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_Identify::_Identify ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "string _Identify::JOIN"

.SS "string _Identify::NICK"

.SS "string _Identify::NickServ"

.SS "string _Identify::USER"


.SH "Author"
.PP 
Generated automatically by Doxygen for IRC from the source code\&.
