.TH "src Directory Reference" 3 "Wed Jun 12 2013" "Version 0.1" "IRC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdaemon\&.cpp\fP"
.br
.ti -1c
.RI "file \fBirc_func\&.cpp\fP"
.br
.ti -1c
.RI "file \fBirc_func\&.h\fP"
.br
.ti -1c
.RI "file \fBirc_sqlite3\&.cpp\fP"
.br
.ti -1c
.RI "file \fBirc_sqlite3\&.h\fP"
.br
.ti -1c
.RI "file \fBircbot\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.in -1c
