.TH "src Directory Reference" 3 "Mon Jun 3 2013" "IRCBot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBirc_func\&.cpp\fP"
.br
.ti -1c
.RI "file \fBirc_func\&.h\fP"
.br
.ti -1c
.RI "file \fBirc_sqlite3\&.cpp\fP"
.br
.ti -1c
.RI "file \fBirc_sqlite3\&.h\fP"
.br
.ti -1c
.RI "file \fBircbot\&.cpp\fP"
.br
.in -1c
