.TH "src/irc_sqlite3.cpp" 3 "Wed Jun 12 2013" "Version 0.1" "IRC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/irc_sqlite3.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <sqlite3\&.h>\fP
.br
\fC#include 'irc_sqlite3\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBirc_sqlite3_cpp__\fP"
.br
.ti -1c
.RI "#define \fBsqlite3Path\fP   'log\&.sqlite3'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsql_init\fP ()"
.br
.ti -1c
.RI "void \fBsql_close\fP ()"
.br
.ti -1c
.RI "void \fBsql_createtables\fP ()"
.br
.ti -1c
.RI "void \fBsql_delete\fP ()"
.br
.ti -1c
.RI "void \fBsql_addchat\fP (const char name[], const char channel[], const char chat[], const char date[])"
.br
.ti -1c
.RI "std::string \fBsql_lastseen\fP (const char name[])"
.br
.ti -1c
.RI "std::string \fBsql_getchat\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "sqlite3 * \fBsqlitedb\fP = NULL"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define irc_sqlite3_cpp__"

.SS "#define sqlite3Path   'log\&.sqlite3'"

.SH "Function Documentation"
.PP 
.SS "void sql_addchat (const charname[], const charchannel[], const charchat[], const chardate[])"

.SS "void sql_close ()"

.SS "void sql_createtables ()"

.SS "void sql_delete ()"

.SS "std::string sql_getchat ()"

.SS "void sql_init ()"

.SS "std::string sql_lastseen (const charname[])"

.SH "Variable Documentation"
.PP 
.SS "sqlite3* sqlitedb = NULL"

.SH "Author"
.PP 
Generated automatically by Doxygen for IRC from the source code\&.
