.TH "src/irc_sqlite3.h" 3 "Wed Jun 12 2013" "Version 0.1" "IRC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/irc_sqlite3.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsql_init\fP ()"
.br
.ti -1c
.RI "void \fBsql_close\fP ()"
.br
.ti -1c
.RI "void \fBsql_createtables\fP ()"
.br
.ti -1c
.RI "void \fBsql_delete\fP ()"
.br
.ti -1c
.RI "void \fBsql_addchat\fP (const char name[], const char channel[], const char chat[], const char date[])"
.br
.ti -1c
.RI "std::string \fBsql_lastseen\fP (const char name[])"
.br
.ti -1c
.RI "std::string \fBsql_getchat\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void sql_addchat (const charname[], const charchannel[], const charchat[], const chardate[])"

.SS "void sql_close ()"

.SS "void sql_createtables ()"

.SS "void sql_delete ()"

.SS "std::string sql_getchat ()"

.SS "void sql_init ()"

.SS "std::string sql_lastseen (const charname[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for IRC from the source code\&.
