.TH "src/irc_sqlite3.h" 3 "Mon Jun 3 2013" "IRCBot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/irc_sqlite3.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsql_init\fP ()"
.br
.ti -1c
.RI "void \fBsql_close\fP ()"
.br
.ti -1c
.RI "void \fBsql_createtables\fP ()"
.br
.ti -1c
.RI "void \fBsql_delete\fP ()"
.br
.ti -1c
.RI "void \fBsql_addchat\fP (const char name[], const char channel[], const char chat[], const char date[])"
.br
.ti -1c
.RI "void \fBsql_lastseen\fP (const char name[])"
.br
.ti -1c
.RI "void \fBsql_getchat\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void sql_addchat (const charname[], const charchannel[], const charchat[], const chardate[])"

.PP
Definition at line 48 of file irc_sqlite3\&.cpp\&.
.SS "void sql_close ()"

.PP
Definition at line 33 of file irc_sqlite3\&.cpp\&.
.SS "void sql_createtables ()"

.PP
Definition at line 38 of file irc_sqlite3\&.cpp\&.
.SS "void sql_delete ()"

.PP
Definition at line 43 of file irc_sqlite3\&.cpp\&.
.SS "void sql_getchat ()"

.PP
Definition at line 73 of file irc_sqlite3\&.cpp\&.
.SS "void sql_init ()"

.PP
Definition at line 25 of file irc_sqlite3\&.cpp\&.
.SS "void sql_lastseen (const charname[])"

.PP
Definition at line 55 of file irc_sqlite3\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for IRCBot from the source code\&.
