.TH "Ircbot" 3 "Wed Jun 12 2013" "Version 0.1" "IRC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ircbot \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBport\fP"
.br
.ti -1c
.RI "string \fBserver\fP"
.br
.ti -1c
.RI "string \fBchannel\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string Ircbot::channel"

.SS "string Ircbot::name"

.SS "string Ircbot::port"

.SS "string Ircbot::server"


.SH "Author"
.PP 
Generated automatically by Doxygen for IRC from the source code\&.
