.TH "src/ircbot.cpp" 3 "Mon Jun 3 2013" "IRCBot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ircbot.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'irc_sqlite3\&.h'\fP
.br
\fC#include 'irc_func\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Definition at line 21 of file ircbot\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for IRCBot from the source code\&.
