.TH "src/ircbot.cpp" 3 "Wed Jun 12 2013" "Version 0.1" "IRC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ircbot.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'irc_sqlite3\&.h'\fP
.br
\fC#include 'irc_func\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for IRC from the source code\&.
