.TH "src/main.cpp" 3 "Wed Jun 12 2013" "Version 0.1" "IRC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBIrcbot\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBIrcbot\fP \fBmyIrcbot\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "string & \fBgetfile\fP (const string &filename, string &buffer)"
.br
.ti -1c
.RI "void \fBtest\fP ()"
.br
.ti -1c
.RI "void \fBfilldatas\fP (\fBIrcbot\fP &\fBbot\fP, string datas)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmyIrcbot\fP * \fBbot\fP"
.br
.ti -1c
.RI "pid_t * \fBpID\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBIrcbot\fP \fBmyIrcbot\fP"

.SH "Function Documentation"
.PP 
.SS "void filldatas (\fBIrcbot\fP &bot, stringdatas)"

.SS "string & getfile (const string &filename, string &buffer)"

.SS "int main ()"

.SS "void test ()"

.SH "Variable Documentation"
.PP 
.SS "\fBmyIrcbot\fP* bot"

.SS "pid_t* pID"

.SH "Author"
.PP 
Generated automatically by Doxygen for IRC from the source code\&.
